#!/bin/bash

source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/directories.sh

FILE_NAME=$1
CONTENT_TYPE="component"
TEMPLATE_DIR="generate/templates"
DESTINATION_DIR="src/components"

check_for_name "$FILE_NAME"
flags_result=$(process_flags "$@")
eval "flags=($flags_result)"
MAIN_NAME=$(create_pascal_case_name "$FILE_NAME")
ensure_directories_exist "$DESTINATION_DIR"

sed "s/{{MAIN_NAME}}/$MAIN_NAME/g" "$TEMPLATE_DIR/$CONTENT_TYPE" > "$DESTINATION_DIR/$FILE_NAME.tsx"

sed -e "s/{{MAIN_NAME}}/$MAIN_NAME/g" -e "s/{{FILE_NAME}}/$FILE_NAME/g" "$TEMPLATE_DIR/$CONTENT_TYPE.test" > "$DESTINATION_DIR/$FILE_NAME.test.tsx"

if [ "${flags["CLIENT_FLAG"]}" = true ]; then
  echo -e "'use client'\n" | cat - "$DESTINATION_DIR/$FILE_NAME.tsx" > temp && mv temp "$DESTINATION_DIR/$FILE_NAME.tsx"
fi

echo "$MAIN_NAME $CONTENT_TYPE created!"
