#!/bin/bash

source generate/helpers/check_for_name.sh
source generate/helpers/process_flags.sh

FILE_NAME=$1
TEMPLATE_DIR="generate/templates"
COMPONENT_DIR="src/components"

check_for_name "$FILE_NAME"
flags_result=$(process_flags "$@")
eval "flags=($flags_result)"

mkdir -p "$COMPONENT_DIR"

IFS="-" read -ra NAME_ARRAY <<< "$FILE_NAME"

COMPONENT_NAME=""

for element in "${NAME_ARRAY[@]}"; do
  COMPONENT_NAME+="$(echo "$element" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')"
done

sed "s/{{COMPONENT_NAME}}/$COMPONENT_NAME/g" "$TEMPLATE_DIR/component" > "$COMPONENT_DIR/$FILE_NAME.tsx"

sed -e "s/{{COMPONENT_NAME}}/$COMPONENT_NAME/g" -e "s/{{FILE_NAME}}/$FILE_NAME/g" "$TEMPLATE_DIR/component.test" > "$COMPONENT_DIR/$FILE_NAME.test.tsx"

if [ "${flags["CLIENT_FLAG"]}" = true ]; then
  echo -e "'use client'\n" | cat - "$COMPONENT_DIR/$FILE_NAME.tsx" > temp && mv temp "$COMPONENT_DIR/$FILE_NAME.tsx"
fi

echo "$COMPONENT_NAME component created!"
