#!/bin/bash

source generate/helpers/validators.sh
source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/content.sh
source generate/helpers/files.sh
source generate/helpers/feedback.sh

FILE_NAME=$1
CONTENT_TYPE="component"
TEMPLATE_DIR="generate/templates"
DESTINATION_DIR="src/components"
INTRO_DIRECTIVE="use client"
EXTENSION="tsx"

check_for_name "$FILE_NAME"
ensure_directories_exist "$DESTINATION_DIR"
process_flags "$@"

MAIN_NAME=$(create_pascal_case_name "$FILE_NAME")
CORE_CONTENT=$(determine_content_for_core "$MAIN_NAME" "$CONTENT_TYPE")
TEST_CONTENT=$(determine_content_for_test "$FILE_NAME" "$MAIN_NAME" "$CONTENT_TYPE")
final_content="$CORE_CONTENT"

if [ "$CLIENT_FLAG" = true ]; then
    final_content=$(prepend_directive_to_content "$INTRO_DIRECTIVE" "$CORE_CONTENT")
fi

create_file "$final_content" "$FILE_NAME" "$DESTINATION_DIR" "$EXTENSION" "false"
create_file "$TEST_CONTENT" "$FILE_NAME" "$DESTINATION_DIR" "$EXTENSION" "true"
confirm_entity_created "$MAIN_NAME" "$CONTENT_TYPE"
