#!/bin/bash

source generate/helpers/validators.sh
source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/content.sh
source generate/helpers/files.sh
source generate/helpers/folders.sh
source generate/helpers/feedback.sh

CORE_PATH="$1"
GROUP="$2"
SRC_DIR="src"
APP_DIR="app"
DIRECTORIES=("$SRC_DIR" "$APP_DIR")
DESTINATION_DIR="$SRC_DIR/$APP_DIR"

check_for_name "$GROUP"
check_for_path "$CORE_PATH"

updated_directories=($(add_path_to_directories "$CORE_PATH" "$DESTINATION_DIR" "${DIRECTORIES[@]}"))
DESTINATION_DIR="${updated_directories[0]}"
DIRECTORIES=("${updated_directories[@]:1}")
DIRECTORIES+=("($GROUP)")

ensure_directories_exist "${DIRECTORIES[@]}"
confirm_entity_created "$GROUP" "group"
