#!/bin/bash

source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/directories.sh
source generate/helpers/content.sh
source generate/helpers/files.sh
source generate/helpers/feedback.sh

FILE_NAME=$1
CONTENT_TYPE="component"
TEMPLATE_DIR="generate/templates"
DESTINATION_DIR="src/components"
INTRO_DIRECTIVE="use client"
EXTENSION="tsx"
