#!/bin/bash

source generate/helpers/validators.sh
source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/content.sh
source generate/helpers/files.sh
source generate/helpers/feedback.sh

CORE_PATH="$1"
FOLDER_NAME="$2"
MAIN_NAME="$2"
SRC_DIR="src"
APP_DIR="app"
API_DIR="api"
CONTENT_TYPE="route"
TEMPLATE_DIR="generate/templates"
DIRECTORIES=("$SRC_DIR" "$APP_DIR" "$API_DIR")
DESTINATION_DIR="$SRC_DIR/$APP_DIR/$API_DIR"
EXTENSION="ts"

process_flags "$@"
check_for_name "$MAIN_NAME"
check_for_path "$CORE_PATH"

if [ "$CORE_PATH" != "/" ]; then
    IFS="/"
    read -ra PATH_DIRS <<<"$CORE_PATH"
    unset IFS

    DIRECTORIES+=("${PATH_DIRS[@]}")
    DESTINATION_DIR+="/$CORE_PATH"
fi

if [ "$DYNAMIC_FLAG" = true ]; then
    FOLDER_NAME="[$FOLDER_NAME]"
fi

DIRECTORIES+=("$FOLDER_NAME")
DESTINATION_DIR+="/$FOLDER_NAME"
cd_list=""

for i in "${DIRECTORIES[@]}"; do
    mkdir -p "$i"
    if [ -d "$i" ]; then
        cd "$i"
        cd_list="../$cd_list"
    fi
done

cd "$cd_list"

CORE_CONTENT=$(determine_content_for_core "$CONTENT_TYPE" "$CONTENT_TYPE")
TEST_CONTENT=$(determine_content_for_test "$CONTENT_TYPE" "$CONTENT_TYPE" "$CONTENT_TYPE")
final_content="$CORE_CONTENT"

create_file "$final_content" "$CONTENT_TYPE" "$DESTINATION_DIR" "$EXTENSION" "false"
create_file "$TEST_CONTENT" "$CONTENT_TYPE" "$DESTINATION_DIR" "$EXTENSION" "true"
confirm_entity_created "$MAIN_NAME" "$CONTENT_TYPE"
