#!/bin/bash

source generate/helpers/validators.sh
source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/content.sh
source generate/helpers/files.sh
source generate/helpers/feedback.sh

FILE_NAME="$1"
CONTENT_TYPE="service"
SRC_DIR="src"
SERVICES_DIR="services"
TEMPLATE_DIR="generate/templates"
DIRECTORIES=("$SRC_DIR" "$SERVICES_DIR")
DESTINATION_DIR="$SRC_DIR/$SERVICES_DIR"
INTRO_DIRECTIVE="use server"
EXTENSION="ts"

process_flags "$@"
check_for_name "$FILE_NAME"
ensure_directories_exist "${DIRECTORIES[@]}"

MAIN_NAME=$(create_camel_case_name "$FILE_NAME")
CORE_CONTENT=$(determine_content_for_core "$MAIN_NAME" "$CONTENT_TYPE")
TEST_CONTENT=$(determine_content_for_test "$FILE_NAME" "$MAIN_NAME" "$CONTENT_TYPE")
final_content=$(inject_call_into_service "$CORE_CONTENT" "$FETCH_FLAG")

if [ "$SERVER_FLAG" == true ]; then
    final_content=$(prepend_directive_to_content "$INTRO_DIRECTIVE" "$final_content")
fi

create_file "$final_content" "$FILE_NAME" "$DESTINATION_DIR" "$EXTENSION" "false"
create_file "$TEST_CONTENT" "$FILE_NAME" "$DESTINATION_DIR" "$EXTENSION" "true"
confirm_entity_created "$MAIN_NAME" "$CONTENT_TYPE"
