#!/bin/bash

source generate/helpers/names.sh
source generate/helpers/flags.sh
source generate/helpers/directories.sh

FILE_NAME=$1
CONTENT_TYPE="service"
TEMPLATE_DIR="generate/templates"
DESTINATION_DIR="src/services"

check_for_name "$FILE_NAME"
flags_result=$(process_flags "$@")
eval "flags=($flags_result)"
MAIN_NAME=$(create_camel_case_name "$FILE_NAME")
ensure_directories_exist "$DESTINATION_DIR"

sed "s/{{MAIN_NAME}}/$MAIN_NAME/g" "$TEMPLATE_DIR/$CONTENT_TYPE" > "$DESTINATION_DIR/$FILE_NAME.ts"

sed -e "s/{{MAIN_NAME}}/$MAIN_NAME/g" -e "s/{{FILE_NAME}}/$FILE_NAME/g" "$TEMPLATE_DIR/$CONTENT_TYPE.test" > "$DESTINATION_DIR/$FILE_NAME.test.ts"

if [ "${flags["SERVER_FLAG"]}" = true ]; then
  echo -e "'use server'\n" | cat - "$DESTINATION_DIR/$FILE_NAME.ts" > temp && mv temp "$DESTINATION_DIR/$FILE_NAME.ts"
fi

echo "$MAIN_NAME $CONTENT_TYPE created!"
