#!/bin/bash

source generate/helpers/names.sh
source generate/helpers/directories.sh

FILE_NAME=$1
CONTENT_TYPE="utility"
TEMPLATE_DIR="generate/templates"
DESTINATION_DIR="src/utilities"

check_for_name "$FILE_NAME"
MAIN_NAME=$(create_camel_case_name "$FILE_NAME")
ensure_directories_exist "$DESTINATION_DIR"

sed "s/{{MAIN_NAME}}/$MAIN_NAME/g" "$TEMPLATE_DIR/$CONTENT_TYPE" > "$DESTINATION_DIR/$FILE_NAME.ts"

sed -e "s/{{MAIN_NAME}}/$MAIN_NAME/g" -e "s/{{FILE_NAME}}/$FILE_NAME/g" "$TEMPLATE_DIR/$CONTENT_TYPE.test" > "$DESTINATION_DIR/$FILE_NAME.test.ts"

echo "$MAIN_NAME $CONTENT_TYPE created!"
