name: Ask a Question
description: Create a new ticket to ask a question
labels: ['question']
assignees:
  - jtreeves
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our documentation, especially the [README](https://github.com/jtreeves/read-this-next)
        - Ensure the question has not already been [asked](https://github.com/jtreeves/read-this-next/labels/question)
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What topic would you like to discuss?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Can you provide any additional context to help us understand your question?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/jtreeves/read-this-next?tab=coc-ov-file#readme)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
