name: Post-Deploy Checks
on:
  deployment_status:
jobs:
  e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run end-to-end tests
        run: npm run test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: https://read-this-next.vercel.app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  issue-creation:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: failure()
    steps:
      - uses: actions/checkout@v4
      - name: Create issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Failure occurred when running e2e tests
          body: One or more end-to-end tests failed after the latest deployment.
          labels: tests
          assignees: jtreeves
